name = "LidJul"
uuid = "f4240088-3779-5595-97ea-a3d81402903f"
version = "0.3.0"
authors = ["Laurent Plagne <laurent.plagne@gmail.com>"]

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[extensions]
LidJulMakieExt = "Makie"
LidJulPlotlyExt = "PlotlyBase"

[compat]
julia = "1.13"
AlgebraicMultigrid = "2.0.2"
IncompleteLU = "0.2.1"
IterativeSolvers = "0.9.4"
LinearAlgebra = "1.13.0"
SparseArrays = "1.13.0"
PlotlyBase = "0.10.0"
Makie = "0.24.15"
Test = "1.11"

[extras]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PlotlyBase"]
